### ISSUE TITLE
Support typescript:main, module, and jsnext:main in package.json

### ISSUE THREAD

**Issue by appsforartists** [steelbrain/pundle#109] opened 2017-01-16 17:11 UTC
In `package.json`, `main` refers to a file that uses CommonJS to handle importing/exporting other files.  There are other standards for other module formats:

For TypeScript, [`typescript:main`](https://github.com/Microsoft/TypeScript/issues/12561/)
For ES2015 `import`/`export` statements, [`module`](https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md) and [`jsnext:main`](https://github.com/rollup/rollup/wiki/jsnext:main/22b87213d6dcb70c77e2e51ba102e4819697bb1c)

The relevant Pundle presets (e.g. TypeScript and Babel) should prefer these keys by default.

**Comment by steelbrain** [comment] 2017-01-16 17:12
Sounds fair

**Comment by appsforartists** [comment] 2017-01-16 17:17
This is especially nice if you're working across many modules.  It lets you edit the source of a dependency and still get HMR without needing to run a build step in the middle.

**Comment by steelbrain** [comment] 2017-01-16 17:25
Fixed as of https://github.com/motion/pundle/commit/0d7214b
I've added `module`, but not `jsnext:main` mainly because it's specific to a package and we want to keep things like that configurable to the user. but `module` seems more like a standard and also supersedes `jsnext:main` so that shouldn't be a problem.

**Comment by appsforartists** [comment] 2017-01-17 06:06
`module` seems to work with TypeScript.  I tested by importing this module:

https://github.com/appsforartists/MidiConvert/commit/6bdb7dedd60000064f5fc75a69932b5ec6148b2e

Want to add it back to the TS preset for beta9?

**Comment by steelbrain** [comment] 2017-01-17 09:12
Readded as of https://github.com/motion/pundle/commit/27420f8

**Comment by appsforartists** [comment] 2017-01-20 03:48
Using this config in `.pundle`:

```javascript
  presets: [
    [
      require.resolve('pundle-preset-default'),
      {
        loader: false,
      }
    ],
    [
      require.resolve('pundle-preset-typescript'),
      {
        resolver: {
          packageMains: ['typescript:main', 'browser', 'main'],
        },
        transformer: {
          extensions: ['js', 'jsx', 'ts', 'tsx'],
          exclude: [],
          config: {
            compilerOptions: Object.assign(
              mainTSConfig.compilerOptions,
              tsConfig.compilerOptions
            )
          }
        }
      }
    ],
  ],
```

Resolver is seeing this config:

```javascript
{ alias: {},
  extensions: null,
  packageMains: [ 'browser', 'browserify', 'webpack', 'main' ],
  modulesDirectories: [ 'node_modules' ],
  knownExtensions: [ '', 'js', 'jsx', 'json', 'ts', 'tsx' ] }
```
In all places that `config.packageMains` appears in this file:

https://github.com/motion/pundle/blob/f893148bd7e322a36754d9ddc00f5bf80d70bea0/packages/resolver-default/src/index.js#L80

Moving the `resolver` block into `pundle-preset-default` corrects `packageMains`.  Are you sure the resolver is looking in other presets for its configuration.

**Comment by steelbrain** [comment] 2017-01-20 09:38
In addition to having `loader: false`, you should also do `resolver: false` in default preset. The problem is ocurring because default loader is resolving it before it gets to the typescript loader, and exts are the same between the two

**Comment by appsforartists** [comment] 2017-01-21 02:06
Adding `resolver: false` breaks imports:

```
  Error   Cannot find module './lib/ReactDOM' from 'node_modules/react-dom/index.js'
```

**Comment by steelbrain** [comment] 2017-01-23 17:46
I've put a working pundle configuration for your project in [a gist](https://gist.github.com/steelbrain/01c8a7ff625ab972e4f700562529da40). It doesn't look very nice right now, and is not the most pleasant thing to configure.

I'm going to change that in the upcoming releases so the end user only has to specify `extensions` or any other config once per preset and the preset can apply that one config at multiple places.

I've opened https://github.com/motion/pundle/issues/117 to track it

**Closed as completed by steelbrain** 2017-01-23 17:46 UTC
